[package]
name = "rusty-merkle-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
digest = "0.8.1"
sha3 = "0.9.0"
shlex = "1.3.0"
termios = "0.3.3"
